- name: Set named.conf
  copy:
    src: named.conf
    dest: /etc/named.conf
- name: Set named.conf.okd.gomel.iba.by
  copy:
    src: named.conf.okd.gomel.iba.by
    dest: /etc/named/named.conf.okd.gomel.iba.by
- name: Create Bind zones dir
  file:
    path: /var/named/zones
    state: directory
- name: Set zone DB file
  copy:
    src: zones/db.okd.gomel.iba.by
    dest: /var/named/zones/db.okd.gomel.iba.by
- name: Set reverse zone DB file
  copy:
    src: zones/db.10.224.0
    dest: /var/named/zones/db.10.224.0
- name: Restart Bind DNS
  systemd:
    service: named
    state: restarted
- name: Allow okd subnet to use DNS
  firewalld:
    rich_rule: rule family=ipv4 source address=10.224.0.0/19 service name=dns accept
    zone: public
    permanent: yes
    immediate: yes
    state: enabled
- name: Allow ibagomel to use DNS
  firewalld:
    rich_rule: rule family=ipv4 source address=172.27.0.0/16 service name=dns accept
    zone: public
    permanent: yes
    immediate: yes
    state: enabled
