---
  apiVersion: v1
  baseDomain: okd.gomel.iba.by
  compute:
  - hyperthreading: Enabled   
    name: worker
    replicas: 0
  controlPlane:
    hyperthreading: Enabled   
    name: master 
    replicas: 3 
  metadata:
    name: okd4
  networking:
    clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23 
    networkType: OpenShiftSDN
    serviceNetwork:
    - 172.30.0.0/16
  platform:
    none: {} 
  pullSecret: '{"auths":{"fake":{"auth": "bar"}}}'
  sshKey: '{{ ssh_public_key }}'
