- name: Get ssh key from environment variable
  set_fact:
    ssh_public_key: "{{ lookup('env','OKD_PUBLIC_KEY') }}"
- name: Fail if SSH key is not defined
  fail: msg="Public key not found - should be exported as $OKD_PUBLIC_KEY"
  when: ssh_public_key == ''
- name: Check if path to pull secret file is provided
  fail: 
    msg: |
          Path to pull secret file is not provided
          Use pull_secret_file ansible variable to provide the path
  when: pull_secret_file is undefined
- name: Get pull secret from file
  set_fact:
    pull_secret: "{{ lookup('file', pull_secret_file) }}"
- name: Purge /tmp directory (hidden files are created after generating the configs, and they should be removed)
  shell:
    chdir: /tmp
    cmd: ls -A1 | xargs rm -rf
- name: Generate input for Ignition config
  template:
    src: install-config.yaml
    dest: /tmp/install-config.yaml
- name: Generate manifests and ignition config
  command: chdir=/tmp {{ item }}
  with_items:
  - openshift-install create manifests
  - openshift-install create ignition-configs